### PR TITLE
update to v4.1.0

### PR DESCRIPTION
**Pull request by elmarco**

### CODE REVIEW

**Comment by elmarco** [comment]
you may need to pull the tags too

**Comment by arcnmx** [comment]
Oh nice, thanks! Hopefully can get around to cleaning up and testing some of these crates soon...

**Comment by elmarco** [comment]
I would like to play with async, but I can't decide yet whether it should be tokio or async-std or something else. I am still a bit confused. Otherwise, I might tackle something from https://github.com/arcnmx/qapi-rs/issues/2#issuecomment-391192441

**Comment by arcnmx** [comment]
Yeah, I'd basically put a number of crates on hold waiting for it, now that a{sync,wait} are nearing release I plan on starting to pick them up again when I can. I aim to be agnostic to the runtime by mostly just relying on the underlying futures traits but it can get hairy in a few places.

**Pull request merged**
